package Lexico;

/**
 * @author Juan Ruiz
 * @author Juan Pinzon
 */
public enum Categoria {

    ENTERO,
    REAL,
    PUNTO,
    DOS_PUNTOS,
    IDENTIFICADOR,
    CADENA_CARACTERES,
    OPERADOR_ARTIMETICO,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    OPERADOR_ASIGNACION,
    OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,
    PARENTESIS_ABIERTO,
    PARENTESIS_CERRADO,
    LLAVE_ABIERTA,
    LLAVE_CERRADA,    
    TERMINAL,
    SEPARADOR,
    COMENTARIO,
    DESCONOCIDO,
    PALABRA_RESERVADA,
    ERROR_CADENA_CARACTERES,
    CARACTER,
    ERROR_OPERADOR_DECREMENTO,
    ERROR_OPERADOR_INCREMENTO,
    ERROR_COMENTARIO_BLOQUE,
    ERROR_COMENTARIO_LINEA,
    COMENTARIO_BLOQUE,
    COMENTARIO_LINEA,
    CORCHETE_ABIERTO,
    CORCHETE_CERRADO,
    FIN_DE_SENTENCIA,
    ERROR_CARACTER
}
